#!/bin/bash

VOLTAGE_HISTSIZE=$VOLTAGE_HISTORY_SIZE
VOLTAGE1_HISTSIZE=$VOLTAGE1_HISTORY_SIZE
VOLTAGE2_HISTSIZE=$VOLTAGE2_HISTORY_SIZE
VOLTAGE=(${VOLTAGE_HISTORY//,/ })
VOLTAGE1=(${VOLTAGE1_HISTORY//,/ })
VOLTAGE2=(${VOLTAGE2_HISTORY//,/ })

PUSHSW_HISTSIZE=$PUSHSW_HISTORY_SIZE
PUSHSW=(${PUSHSW_HISTORY//,/ })

EXTIN_HISTSIZE=$EXTIN_HISTORY_SIZE
EXTIN=(${EXTIN_HISTORY//,/ })
